CXX = c++

CXXFLAGS = -g -Wall -Wextra -std=c++98

SRC = main.cpp 

OBJ = $(SRC:.cpp=.o)

NAME = PmergeMe

all : $(NAME)

$(NAME) : $(OBJ)
	$(CXX) $(CXXFLAGS) $(OBJ) -o $(NAME)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean :
	rm -f $(OBJ)
	
fclean : clean
	rm -f $(NAME)

re : fclean all

.PHONY : all clean fclean re
