CXX = c++

CXXFLAGS = -Wall -Wextra -Werror 

SRC = main.cpp utils.cpp ScalarConverter.cpp

OBJ = $(SRC:.cpp=.o)

NAME = exe

all : $(NAME)

$(NAME) : $(OBJ)
	$(CXX) $(CXXFLAGS) $(OBJ) -o $(NAME)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean :
	rm -f $(OBJ)
	
fclean : clean
	rm -f $(NAME)

re : fclean all

.PHONY : all clean fclean re